[package]
name = "please-dont-escape"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/slowchop/please-dont-escape"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.5"
bevy_egui = "0.6"
nalgebra = "0.29.0"
pathfinding = "2.0"
rand = "*"
